name: 'Upload BOM to Dependency-Track'
author: Patrick Dwyer, Purav Shah
description: 'Uploads a CycloneDX software bill of materials to a Dependency-Track server'
inputs:
  apidomain:
    description: 'Dependency-Track hostname'
    required: true
  apikey:
    description: 'Dependency-Track API key'
    required: true
  projectname:
    description: 'Project name in Dependency-Track'
    required: true
  projectversion:
    description: 'Project version in Dependency-Track'
    default: '1.0.0'
    required: true
  bomfile:
    description: 'Path and filename of the BOM'
    default: 'sbom.cdx.json'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
